// src/types/semantics.ts

// 🎯 Content Type Semantics
export type VoteType = 
  'Upvote' 
  | 'Downvote' 
  | 'None'
  
// 🎯 Content Type Semantics
export type ContentType = 
  'Account' 
  | 'Tale' 
  | 'Insight' 
  | 'Comment'
  | 'Authoring'
  | 'Role'
  
// 🎯 Content Type Semantics
export type LimitedContentType = 
  'Tale' 
  | 'Insight' 
  
// 🎯 Activity Type Semantics
  export type ActivityType =

  // Account
   'CreatedAccount_Account'
   | 'LoggedIn_Account'
   | 'LoggedOut_Account'
   | 'ChangedPassword_Account'
   | 'ResetPassword_Account'
   | 'UpdatedProfile_Account'
   | 'UpdatedProfilePhoto_Account'
   | 'AddedContact_Account'
   | 'UpdatedContact_Account'
   | 'AccountBanned_Account'
   | 'AccountReinstated_Account'
   | 'AccountSuspended_Account'
   | 'AccountModerated_Account'
   | 'ModerationApplied_Account'
   | 'AccountMilestoned_Account'

  // Role
   | 'RoleAssigned_Role'
   | 'RoleReassigned_Role'
   | 'RoleDeactivated_Role'
   | 'RoleActivated_Role'

  // Writer
   | 'WriterOnboarded_Authoring'
   | 'WritingPrivilegeSuspended_Authoring'
   | 'WritingPrivilegeReinstated_Authoring'

  // Tale
   | 'TaleCreated_Tale'
   | 'TaleLaunched_Tale'
   | 'TaleLaunched'
   | 'TaleUpdated_Tale'
   | 'TaleSelfDeleted_Tale'
   | 'TaleSelfArchived_Tale'
   | 'TaleSelfUnarchived_Tale'
   | 'TaleSummaryUpdated_Tale'
   | 'TaleDetailUpdated_Tale'
   | 'TaleCountryUpdated_Tale'
   | 'TaleWatchlistUpdated_Tale'
   | 'TalePhotoUpdated_Tale'
   | 'TaleSuspended_Tale'
   | 'TaleModerated_Tale'
   | 'TaleHasEngagement_Tale'
   | 'TaleArchived_Tale'
   | 'TaleAddendumUpdated_Tale'
   | 'TaleTagged_Tale'
   | 'TaleUntagged_Tale'
   | 'TaleCertified_Tale'
   | 'TaleMilestoned_Tale'

  // Insight
   | 'InsightCreated_Insight'
   | 'InsightLaunched_Insight'
   | 'InsightLaunched'
   | 'InsightUpdated_Insight'
   | 'InsightSelfArchived_Insight'
   | 'InsightSelfUnarchived_Insight'
   | 'InsightSummaryUpdated_Insight'
   | 'InsightDetailUpdated_Insight'
   | 'InsightCountryUpdated_Insight'
   | 'InsightPhotoUpdated_Insight'
   | 'InsightArchived_Insight'
   | 'InsightAddendumUpdated_Insight'
   | 'InsightTagged_Insight'
   | 'InsightUntagged_Insight'
   | 'InsightSelfDeleted_Insight'
   | 'InsightCertified_Insight'
   | 'InsightSuspended_Insight'
   | 'InsightModerated_Insight'
   | 'InsightMilestoned_Insight'

  // Comment
   | 'Commented_Comment'
   | 'Replied_Comment'
   | 'CommentReplied_Comment'
   | 'CommentSelfDeleted_Comment'
   | 'CommentSelfArchived_Comment'
   | 'CommentSuspended_Comment'
   | 'CommentModerated_Comment'
   | 'CommentArchived_Comment'
   | 'CommentCertified_Comment'
   | 'CommentAddendumUpdated_Comment'
   | 'CommentUpdated_Comment'
   | 'ReplySelfDeleted_Comment'
   | 'CommentMilestoned_Comment'

  // Engagement
   | 'ContentSavedToFavorites_Engagement'
   | 'ContentRemovedFromFavorites_Engagement'
   | 'ContentRestoredToFavorites_Engagement'
   | 'ContentFlagged_Engagement'
   | 'ContentShared_Engagement'
   | 'ContentUpvoted_Engagement'
   | 'ContentDownvoted_Engagement'

// 1. Core domain enumeration 
export type Category =
  'PoliticsGovernance'
  | 'Sports'
  | 'FashionEntertainment'
  | 'Education'
  | 'ScienceTechnology'
  | 'BusinessEconomy'
  | 'MedicineHealthcare'
  | 'LawOrder'
  | 'HumanInterestLifestyle'
  | 'HistoryCulture'
  | 'TheEnvironment'
  | 'Miscellaneous'


// 🎯 Content Type Semantics
export type AccountStatus = 
  'Active' 
  | 'HiddenByModeration' 
  | 'SuspendedByAdmin' 
  | 'BannedByAdmin'

// 🎯 Content Type Semantics
export type ContactType = 
  'Email' 
  | 'Facebook' 
  | 'Twitter' 
  | 'LinkedIn'

// src/enums/Country.ts

// Union type of all ISO codes
export type Country =
  | 'AF'
  | 'AL'
  | 'DZ'
  | 'AD'
  | 'AO'
  | 'AG'
  | 'AR'
  | 'AM'
  | 'AU'
  | 'AT'
  | 'AZ'
  | 'BS'
  | 'BH'
  | 'BD'
  | 'BB'
  | 'BY'
  | 'BE'
  | 'BZ'
  | 'BJ'
  | 'BT'
  | 'BO'
  | 'BA'
  | 'BW'
  | 'BR'
  | 'BN'
  | 'BG'
  | 'BF'
  | 'BI'
  | 'CV'
  | 'KH'
  | 'CM'
  | 'CA'
  | 'CF'
  | 'TD'
  | 'CL'
  | 'CN'
  | 'CO'
  | 'KM'
  | 'CD'
  | 'CG'
  | 'CR'
  | 'HR'
  | 'CU'
  | 'CY'
  | 'CZ'
  | 'DK'
  | 'DJ'
  | 'DM'
  | 'DO'
  | 'EC'
  | 'EG'
  | 'SV'
  | 'GQ'
  | 'ER'
  | 'EE'
  | 'SZ'
  | 'ET'
  | 'FJ'
  | 'FI'
  | 'FR'
  | 'GA'
  | 'GM'
  | 'GE'
  | 'DE'
  | 'GH'
  | 'GR'
  | 'GD'
  | 'GT'
  | 'GN'
  | 'GW'
  | 'GY'
  | 'HT'
  | 'HN'
  | 'HU'
  | 'IS'
  | 'IN'
  | 'ID'
  | 'IR'
  | 'IQ'
  | 'IE'
  | 'IL'
  | 'IT'
  | 'CI'
  | 'JM'
  | 'JP'
  | 'JO'
  | 'KZ'
  | 'KE'
  | 'KI'
  | 'KP'
  | 'KR'
  | 'XK'
  | 'KW'
  | 'KG'
  | 'LA'
  | 'LV'
  | 'LB'
  | 'LS'
  | 'LR'
  | 'LY'
  | 'LI'
  | 'LT'
  | 'LU'
  | 'MG'
  | 'MW'
  | 'MY'
  | 'MV'
  | 'ML'
  | 'MT'
  | 'MH'
  | 'MR'
  | 'MU'
  | 'MX'
  | 'FM'
  | 'MD'
  | 'MC'
  | 'MN'
  | 'ME'
  | 'MA'
  | 'MZ'
  | 'MM'
  | 'NA'
  | 'NR'
  | 'NP'
  | 'NL'
  | 'NZ'
  | 'NI'
  | 'NE'
  | 'NG'
  | 'MK'
  | 'NO'
  | 'OM'
  | 'PK'
  | 'PW'
  | 'PS'
  | 'PA'
  | 'PG'
  | 'PY'
  | 'PE'
  | 'PH'
  | 'PL'
  | 'PT'
  | 'QA'
  | 'RO'
  | 'RU'
  | 'RW'
  | 'KN'
  | 'LC'
  | 'VC'
  | 'WS'
  | 'SM'
  | 'ST'
  | 'SA'
  | 'SN'
  | 'RS'
  | 'SC'
  | 'SL'
  | 'SG'
  | 'SK'
  | 'SI'
  | 'SB'
  | 'SO'
  | 'ZA'
  | 'SS'
  | 'ES'
  | 'LK'
  | 'SD'
  | 'SR'
  | 'SE'
  | 'CH'
  | 'SY'
  | 'TW'
  | 'TJ'
  | 'TZ'
  | 'TH'
  | 'TL'
  | 'TG'
  | 'TO'
  | 'TT'
  | 'TN'
  | 'TR'
  | 'TM'
  | 'TV'
  | 'UG'
  | 'UA'
  | 'AE'
  | 'GB'
  | 'US'
  | 'UY'
  | 'UZ'
  | 'VU'
  | 'VA'
  | 'VE'
  | 'VN'
  | 'YE'
  | 'ZM'
  | 'ZW'

// 🎯 Content Type Semantics
export type WriterStatus = 
  'Initializing' 
  | 'Unauthenticated' 
  | 'Failed'
  | 'None' 
  | 'Active'
  | 'Suspended'

export type TaleStatus =
  | 'Created'
  | 'LaunchedByCreator'
  | 'HiddenByModeration'
  | 'HiddenByAdmin'
  | 'CertifiedByAdmin'
  | 'ArchivedByAdmin'
  | 'LaunchedToArchivedByCreator'
  | 'CertifiedToArchivedByCreator'


export type SortType =
  | 'MostRecent'
  | 'LeastRecent'
  | 'MostViewed'
  | 'MostUpvoted'
  | 'MostFavorited'
  | 'MostCommented'
  | 'MostShared'
  | 'MostFlagged'

  export type GeneralSortType =
  | 'MostRecent'
  | 'LeastRecent'
 

export type InsightStatus =
  | 'Created'
  | 'LaunchedByCreator'
  | 'HiddenByModeration'
  | 'HiddenByAdmin'
  | 'CertifiedByAdmin'
  | 'ArchivedByAdmin'
  | 'LaunchedToArchivedByCreator'
  | 'CertifiedToArchivedByCreator'

  
export type CommentStatus =
  | 'Active'
  | 'HiddenByModeration'
  | 'HiddenByAdmin'
  | 'CertifiedByAdmin'
  | 'ArchivedByAdmin'
  | 'ActiveToArchivedByCreator'
  | 'CertifiedToArchivedByCreator'

// 🎯 Content Type Semantics
export type FlagType = 
  'Other' 
  | 'Misinformation' 
  | 'GraphicContent' 
  | 'AdvocatesViolence'
  | 'HateSpeech' 
  | 'SexualExploitation' 
  | 'ChildAbuse'